kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: udn-gc-bc
  namespace: tfnsw-mq-ace
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'rangin.jfrog.io/ice-ace-docker/rabbitmq:latest' # Replace this with bitbucket location of the stored image
    pushSecret:
      name: rangin-jfrog-user  # need to create a secret in OpenShift containing the username and password of a serviceaccount configured in JFrog
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key  # This secret should be present within the cluster and is used to perform the commands in the Dockerfile
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@github.ibm.com:Langley-Millard/tfnsw-ace-test.git'  # Replace this with bitbucket uri
    sourceSecret:
      name: github-ssh-key # For protected private repositories, SSH key authentication is one method used to clone the repo
  runPolicy: Serial
